# Generated by Django 5.2.13 on 2026-04-29 03:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_desc', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['camera_id'],
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('lot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['lot_id'],
            },
        ),
        migrations.CreateModel(
            name='RLPolicyLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=80)),
                ('state', models.JSONField(default=dict)),
                ('action', models.JSONField(default=dict)),
                ('reward', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=32, unique=True)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('compact', 'Compact'), ('ev', 'EV'), ('disabled', 'Disabled')], default='sedan', max_length=20)),
                ('is_registered', models.BooleanField(default=False)),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('compact', 'Compact'), ('ev', 'EV'), ('disabled', 'Disabled'), ('resident', 'Resident')], default='none', max_length=20)),
            ],
            options={
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='CameraFrameLog',
            fields=[
                ('frame_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frame_uri', models.CharField(max_length=255)),
                ('detected_objects', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_logs', to='parking.camera')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='parking.parkinglot'),
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('spot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=32)),
                ('spot_type', models.CharField(choices=[('standard', 'Standard'), ('compact', 'Compact'), ('ev', 'EV'), ('disabled', 'Disabled')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('disabled', 'Disabled')], default='vacant', max_length=20)),
                ('coord_x', models.FloatField(default=0.0)),
                ('coord_y', models.FloatField(default=0.0)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['lot_id', 'section', 'spot_id'],
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='parking.parkingspot'),
        ),
        migrations.CreateModel(
            name='SensorEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_events', to='parking.camera')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_events', to='parking.parkingspot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('route_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_x', models.FloatField(default=0.0)),
                ('start_y', models.FloatField(default=0.0)),
                ('waypoints', models.JSONField(default=list)),
                ('policy_name', models.CharField(default='heuristic-v1', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='parking.parkingspot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='parking.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingAssignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('occupied', 'Occupied'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('reason', models.CharField(default='heuristic nearest vacant spot', max_length=160)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='parking.parkingspot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='parking.vehicle')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryExit',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='parking.parkingspot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='parking.vehicle')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
