"""DRF serializers that define public API shapes for parking resources."""

from rest_framework import serializers

from .models import (
    Camera,
    CameraFrameLog,
    EntryExit,
    ParkingAssignment,
    ParkingLot,
    ParkingSpot,
    RLPolicyLog,
    RoutePlan,
    SensorEvent,
    Vehicle,
)


class VehicleSerializer(serializers.ModelSerializer):
    """Create, update, and expose registered vehicle data."""

    class Meta:
        model = Vehicle
        fields = ["vehicle_id", "license_plate", "vehicle_type", "is_registered", "discount_type"]


class ParkingLotSerializer(serializers.ModelSerializer):
    """Expose parking lot summary with computed spot counts."""

    vacant_count = serializers.IntegerField(read_only=True)
    occupied_count = serializers.IntegerField(read_only=True)
    reserved_count = serializers.IntegerField(read_only=True)

    class Meta:
        model = ParkingLot
        fields = [
            "lot_id",
            "name",
            "address",
            "total_capacity",
            "lot_width",
            "lot_height",
            "vacant_count",
            "occupied_count",
            "reserved_count",
        ]


class ParkingSpotSerializer(serializers.ModelSerializer):
    """Expose parking spot coordinates and state for map rendering."""

    lot_id = serializers.PrimaryKeyRelatedField(source="lot", queryset=ParkingLot.objects.all())

    class Meta:
        model = ParkingSpot
        fields = ["spot_id", "lot_id", "section", "spot_type", "status", "coord_x", "coord_y"]


class CameraSerializer(serializers.ModelSerializer):
    """Expose camera status and heartbeat metadata."""

    lot_id = serializers.PrimaryKeyRelatedField(source="lot", queryset=ParkingLot.objects.all())
    spot_id = serializers.PrimaryKeyRelatedField(source="spot", queryset=ParkingSpot.objects.all(), allow_null=True, required=False)

    class Meta:
        model = Camera
        fields = ["camera_id", "lot_id", "spot_id", "location_desc", "status", "last_heartbeat"]


class EntryExitSerializer(serializers.ModelSerializer):
    """Expose transaction records with nested display-friendly labels."""

    vehicle_id = serializers.PrimaryKeyRelatedField(source="vehicle", queryset=Vehicle.objects.all())
    spot_id = serializers.PrimaryKeyRelatedField(source="spot", queryset=ParkingSpot.objects.all())
    license_plate = serializers.CharField(source="vehicle.license_plate", read_only=True)
    spot_label = serializers.CharField(source="spot.section", read_only=True)

    class Meta:
        model = EntryExit
        fields = ["transaction_id", "vehicle_id", "license_plate", "spot_id", "spot_label", "entry_time", "exit_time"]


class RoutePlanSerializer(serializers.ModelSerializer):
    """Expose route waypoints generated by heuristic or future RL policies."""

    vehicle_id = serializers.PrimaryKeyRelatedField(source="vehicle", queryset=Vehicle.objects.all())
    target_spot_id = serializers.PrimaryKeyRelatedField(source="target_spot", queryset=ParkingSpot.objects.all())

    class Meta:
        model = RoutePlan
        fields = ["route_id", "vehicle_id", "target_spot_id", "start_x", "start_y", "waypoints", "policy_name", "created_at"]


class SensorEventSerializer(serializers.ModelSerializer):
    """Serialize normalized sensor events from cameras or spot devices."""

    class Meta:
        model = SensorEvent
        fields = ["event_id", "camera", "spot", "event_type", "payload", "created_at"]


class ParkingAssignmentSerializer(serializers.ModelSerializer):
    """Expose assignment state for operations and debugging."""

    class Meta:
        model = ParkingAssignment
        fields = ["assignment_id", "vehicle", "spot", "status", "reason", "assigned_at", "released_at"]


class RLPolicyLogSerializer(serializers.ModelSerializer):
    """Expose RL policy decisions for audit and offline tuning."""

    class Meta:
        model = RLPolicyLog
        fields = ["log_id", "policy_name", "state", "action", "reward", "metadata", "created_at"]


class CameraFrameLogSerializer(serializers.ModelSerializer):
    """Expose CV frame detector logs."""

    class Meta:
        model = CameraFrameLog
        fields = ["frame_id", "camera", "frame_uri", "detected_objects", "created_at"]


class EntryRequestSerializer(serializers.Serializer):
    """Validate vehicle entry simulation input."""

    license_plate = serializers.CharField(max_length=32)
    vehicle_type = serializers.ChoiceField(choices=Vehicle.VEHICLE_TYPES, required=False, default="sedan")
    lot_id = serializers.IntegerField(required=False)


class ExitRequestSerializer(serializers.Serializer):
    """Validate vehicle exit simulation input."""

    license_plate = serializers.CharField(max_length=32)


class HeartbeatSerializer(serializers.Serializer):
    """Validate camera heartbeat state changes."""

    status = serializers.ChoiceField(choices=Camera.STATUSES, required=False, default="online")


class RouteRequestSerializer(serializers.Serializer):
    """Validate route calculation inputs from UI or devices."""

    start = serializers.ListField(child=serializers.FloatField(), min_length=2, max_length=2, required=False)
    target_spot_id = serializers.IntegerField(required=False)
